apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-api.fullname" . }}
  labels:
    {{- include "spring-boot-api.labels" . }}
data:
  {{- toYaml .Values.configMap.config | nindent 2 }}